// <auto-generated />
namespace Zoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Zollein01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zollein01));
        
        string IMigrationMetadata.Id
        {
            get { return "201712171555367_Zollein01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
